/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package petrlgad.txapi

import com.google.gson.Gson
import spark.Request
import spark.Response
import spark.Spark.*
import java.math.BigDecimal

typealias AccountId = String
typealias CurrencyId = String

data class Account(val id: AccountId,
                   val value: BigDecimal,
                   val currency: CurrencyId)

data class Transfer(val from_account_id: AccountId,
                    val to_account_id: AccountId,
                    val amount: BigDecimal,
                    val currency: CurrencyId)

val jsonContentType = "application/json; charset=utf-8"
val GSON = Gson()

fun main(args: Array<String>) {
    port(8080)
    get("/accounts/list") { req: Request, resp: Response ->
        resp.type(jsonContentType)
        GSON.toJson(arrayListOf(
                Account("1", BigDecimal.valueOf(355.0), "EUR"),
                Account("2", BigDecimal.valueOf(45.0), "EUR")
        ))
    }
    put("/accounts/by-id/:id") { req: Request, resp: Response ->
        TODO("Not implemented")
    }
    put("/transfers/by-owner/:owner/by-id/:id") { req: Request, resp: Response ->
        TODO("Not implemented")
    }
}
